### PR TITLE
Update no-unbound-methods.md

### PR DESCRIPTION
**Pull request by aboyton**
Format the code blocks to make them look more similar so that the differences are more obvious.

This is different compared to how Prettier formats them, but I found it really hard to work out what was different when both the code and the formatting was different.

### CODE REVIEW

**Review by cartant — APPROVED** [review]
Yeah, I agree. Thanks.

**Comment by aboyton** [comment]
Well those are some of the fastest code reviews and merges I've ever seen.

Thanks for making this repo and porting over all the rules, especially the two a former colleague of mine wrote (`suffix-subjects` and `no-exposed-subjects`) which you've now migrated for us.

This repo will really help with our migration to ESLint.

**Comment by cartant** [comment]
No worries, I was working in the RxJS repo - on PRs - hence the speedy merges.

**Comment by aboyton** [comment]
Also helps when you're a fellow Aussie and thus in the same timezone.

**Pull request merged**
