### PR TITLE
feat: support Typescript >5

### LINKED ISSUE #109: Typescript 5.0.0 Support?
Could you please provide a version with Typescript 5 support? Your peerDependencies settings prevents using a updated version

### PR DESCRIPTION
**Pull request by AnWeber**
fixes #109

### CODE REVIEW

**Review by cartant — APPROVED** [review]

**Comment by cartant** [comment]
Thanks. There should be a new version published now that includes your change.

**Comment by AnWeber** [comment]
Thx for the fast approval

**Comment by eXpertise7** [comment]
@AnWeber Well, I still get the warning even after update to version 5.0.3:

image

**Comment by AnWeber** [comment]
@eXpertise7 Did you run an `npm upgrade`? [eslint-etc](https://github.com/cartant/eslint-etc/pull/10) and [tsutils-etc](https://github.com/cartant/tsutils-etc/pull/4) also needs updated packages.

**Comment by eXpertise7** [comment]
@AnWeber You're right, it was my bad. I am using Yarn package manager and I've bumped manually version of `eslint-plugin-rxjs` and I've typed `yarn install` command only, which only made changes for main `eslint-plugin-rxjs` package at `yarn.lock` file. Thanks!

**Pull request merged**
